spring.application.name=SecureLogin2
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false

# Configuração de Envio de Email (Projeto de Referência SendEmail)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:seu_email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:sua_senha_de_app}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
